```
version: "2"

services:
  postgresql:
    container_name: 'homeland_postgresql'
    image: postgres:11.5-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  redis:
    container_name: 'homeland_redis'
    image: redis:5.0.5-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
      - ./etc/redis.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf --maxmemory 400mb

  elasticsearch:
    container_name: 'homeland_elasticsearch'
    image: elasticsearch:5-alpine
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx512m"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - '9200'
      - '9300'

  worker:
    build: .
    container_name: 'homeland_worker'
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
      - postgresql
      - redis
    ports: []
    command: bundle exec sidekiq -C config/sidekiq.yml -L /home/app/log/sidekiq.log
    env_file:
      - app.local.env

  web:
    build: .
    container_name: 'homeland_web'
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
      - postgresql
      - redis
      - worker
    ports:
      - 3000:3000
    env_file:
      - app.local.env
```
